name       : chocolate-doom
version    : 3.0.0
release    : 3
source     :
    - https://github.com/chocolate-doom/chocolate-doom/releases/download/chocolate-doom-3.0.0/chocolate-doom-3.0.0.tar.gz : 73aea623930c7d18a7a778eea391e1ddfbe90ad1ac40a91b380afca4b0e1dab8
license    : GPL-2.0
component  : games.action
summary    : Chocolate Doom is a Doom source port that is conservative and historically accurate.
description: |
    Chocolate Doom is a Doom source port that is conservative and historically accurate.
builddeps  :
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/usr/share/games/doom
