name       : chocolate-doom
version    : 3.0.1
release    : 7
source     :
    - https://github.com/chocolate-doom/chocolate-doom/archive/chocolate-doom-3.0.1.tar.gz : a54383beef6a52babc5b00d58fcf53a454f012ced7b1936ba359b13f1f10ac66
license    : GPL-2.0-or-later
component  : games.action
summary    : Chocolate Doom is a Doom source port that is conservative and historically accurate.
description: |
    Chocolate Doom is a Doom source port that is conservative and historically accurate.
builddeps  :
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(libpng)
    - pkgconfig(samplerate)
setup      : |
    %patch -p1 < $pkgfiles/remove_redundant_definition.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
