name       : chocolate-doom
version    : 2.2.1
release    : 1
source     :
    - https://www.chocolate-doom.org/downloads/2.2.1/chocolate-doom-2.2.1.tar.gz : ad11e2871667c6fa0658abf2dcba0cd9b26fbd651ee8df55adfdc18ad8fd674a
license    : GPL-2.0
component  : games.action
summary    : Chocolate Doom is a Doom source port that is conservative and historically accurate.
description: |
    Chocolate Doom is a Doom source port that is conservative and historically accurate.
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
setup      : |
    sed -i 's:/games:/bin:g' src/setup/Makefile.am
    sed -i 's:/games:/bin:g' src/setup/Makefile.in
    sed -i 's:/games:/bin:g' src/Makefile.am
    sed -i 's:/games:/bin:g' src/Makefile.in
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -dm00644 $installdir/usr/share/games/doom
