name       : chocolate-doom
version    : 2.3.0
release    : 2
source     :
    - https://github.com/chocolate-doom/chocolate-doom/releases/download/chocolate-doom-2.3.0/chocolate-doom-2.3.0.tar.gz : 3e6d1a82ac5c8b025a9695ce1e47d0dc6ed142ebb1129b1e4a70e2740f79150c
license    : GPL-2.0
component  : games.action
summary    : Chocolate Doom is a Doom source port that is conservative and historically accurate.
description: |
    Chocolate Doom is a Doom source port that is conservative and historically accurate.
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
setup      : |
    sed -i 's:/games:/bin:g' src/setup/Makefile.am
    sed -i 's:/games:/bin:g' src/setup/Makefile.in
    sed -i 's:/games:/bin:g' src/Makefile.am
    sed -i 's:/games:/bin:g' src/Makefile.in
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -dm00644 $installdir/usr/share/games/doom
